### ISSUE TITLE
Pidgin crashes on startup with plugin loaded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EionRobb/pidgin-opensteamworks#103]
```
What steps will reproduce the problem?
1.Start Pidgin
2.Pidgin crashes

What is the expected output? What do you see instead?
I expect Pidgin to not crash.

What version of the product are you using? On what operating system?
1.5.1 on Windows 7 64-bit

Please provide any additional information below.
The crash message claims libglib as the culprit but the backtrace has libsteam 
in the list and the crash doesn't happen if i remove the libsteam dll from my 
install folder.
```

Original issue reported on code.google.com by `PsychosesMan@gmail.com` on 20 Aug 2015 at 8:24

Attachments:
* [pidgin.RPT](https://storage.googleapis.com/google-code-attachments/pidgin-opensteamworks/issue-103/comment-0/pidgin.RPT)
* [debug.log](https://storage.googleapis.com/google-code-attachments/pidgin-opensteamworks/issue-103/comment-0/debug.log)

**Comment by EionRobb** [comment]
Fixed in 1.6
