### ISSUE TITLE
Newest .so does not get loaded by pidgin.

### ISSUE THREAD

**Issue by Toqozz** [EionRobb/pidgin-opensteamworks#104]
- Put libsteam.so v1.6 from downloads page into ~/.purple/plugins
- Start pidgin
- Steam not in available accounts list, no notification that the plugin has been loaded

Version 1.5.1 works, however it crashes due to the bug with utf-8 characters.

Arch Linux 64bit

**Comment by EionRobb** [comment]
Ah, that's just a 32bit .so so far.  If someone manages to build a 64bit .so I'll throw it up there :)

**Comment by Toqozz** [comment]
Can I build it myself?

**Comment by EionRobb** [comment]
Sure, grab the source, compile with make.  You'll need glib-dev, libpurple-dev and json-glib-dev packages for your distro

**Comment by Toqozz** [comment]
Thanks, here it is: http://filebin.net/sugwbzdb9k

Not sure where to upload.

**Comment by EionRobb** [comment]
Great, thanks.  I've updated the Releases page now :)
