### ISSUE TITLE
How to Install in Windows 7?

### ISSUE THREAD

**Issue by jakeonaut** [EionRobb/pidgin-opensteamworks#106]
It looks like there is a good wiki tutorial on how to install this plugin in Pidgin for Windows, but I cannot access it as the wiki link automatically directs to this github repository. The README is insufficient for installing the plugin on Windows 7 and the suggested methods for installing a third party plugin on Pidgin in Windows are not working.

If anyone has a copy of the old wiki or has this currently set up in Windows and would let me know how I could do the same, I would be very appreciative :)!!!

**Comment by EionRobb** [comment]
How's https://github.com/EionRobb/pidgin-opensteamworks/blob/master/README.md looking now? :)

**Comment by jakeonaut** [comment]
Looks great :)!! Plugin works perfectly!! Thanks so much for this!
