### ISSUE TITLE
json_object_get_string_member: assertion 'node != NULL' failed

### ISSUE THREAD

**Issue by RoBi89** [EionRobb/pidgin-opensteamworks#107]
(Pidgin:18513): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed
    Pidgin 2.10.11 has segfaulted and attempted to dump a core file.
    This is a bug in the software and has happened through
    no fault of your own.

Happens whenever I actually try to enable my steam account.

**Comment by EionRobb** [comment]
Is that with v1.6 of the plugin?

**Comment by RoBi89** [comment]
Ah, my bad, I forgot the version.

No, this is on 1.5.1-1.

**Comment by EionRobb** [comment]
1.6 specifically addresses that crash :)

https://github.com/EionRobb/pidgin-opensteamworks/releases
Give it a try and let me know how you get on.

**Comment by Xylemon** [comment]
Should I still be seeing this annoying message in a terminal with the latest release?

**Comment by EionRobb** [comment]
Yeah, the assertions are from json-glib when we ask it to give us some information that isn't available.  Unfortunately they're a pain to track down exactly what's causing them, but if you do manage to work it out, please open a new issue, this one's about the 1.5 login crash :)
