### ISSUE TITLE
Sometimes double messages from people.

### ISSUE THREAD

**Issue by Toqozz** [EionRobb/pidgin-opensteamworks#111]
Sometimes I receive duplicate messages from people, typically a second or two after the first.

`(07:01:40 PM) friend : that didnt happen last time`
`(07:01:41 PM) friend : that didnt happen last time`

**Comment by EionRobb** [comment]
Are they just the first messages each time the account connects or will it happen sporadically, half way through a connection?

**Comment by Toqozz** [comment]
Can happen any time in a conversation, seemingly at random.

**Comment by Toqozz** [comment]
Issue with pidgin-light, sorry.

**Comment by Toqozz** [comment]
I'm sorry, I am a terrible bug reporter.

This issue seems to occur with the opensteamworks plugin and the facebook plugin, however plugins for services like telegram and skype do not seem to have the issue.

**Comment by Toqozz** [comment]
Problem is in the purple-facebook-git plugin (really).  Closed.
