### ISSUE TITLE
Pidgin Chat won't run while logged into Steam

### ISSUE THREAD

**Issue by vxXJordanXxv** [EionRobb/pidgin-opensteamworks#112]
Anybody know what I am doing wrong? I want to be able to use Pidgin while Steam is logged in and connected. Well I should elaborate it runs but it doesn't function. Any messages I send out while logged in don't register.

**Comment by EionRobb** [comment]
Can you confirm what version of the plugin you're using, on what version of Pidgin, and what OS?  Also, are you able to get a debug log from Pidgin (Help->Debug Window) as you try and send a steam message through Pidgin?
