### ISSUE TITLE
Offline messages repeated

### ISSUE THREAD

**Issue by axel-angel** [EionRobb/pidgin-opensteamworks#114]
Thanks for implementing the offline messages, they work fine generally. The only issue I had so far is that when I'm disconnected in some particular situations (abrupt lose of connection?). Old offline messages are replayed at reconnection. These messages are older than 1 week and it's annoying to see them again and again. Any idea how to debug that?

**Comment by axel-angel** [comment]
I just saw that my comments were imported from here : https://github.com/EionRobb/pidgin-opensteamworks/issues/96 . Is that fixed in the new 1.6 version? Will test it soon.

**Comment by EionRobb** [comment]
Yep, fixed in 1.6.  Did it work for you?

**Comment by axel-angel** [comment]
Ok, I've build from master and give it a try during this week. I'll report it my results. You can safely close this issue in 7 days if I don't reply.

Anyway, thanks for your support and the great work! Super valuable to me.

**Comment by axel-angel** [comment]
Nothing to signal, worked perfectly fine! Thanks for the fix.
