### ISSUE TITLE
Readme instructions for building don't work

### ISSUE THREAD

**Issue by mic-e** [EionRobb/pidgin-opensteamworks#115]
The readme says to download the tarball from the releases section, then `make` and `make install`.

However, the tarball's root doesn't contain a Makefile, and the Makefile just builds `libsteam.so` without offering an `install` option.

**Comment by EionRobb** [comment]
Thanks for that.  Have added the `make install` option to the Makefile, and updated the Readme to point to the steam-mobile subfolder
