### ISSUE TITLE
Gnome Keyring a required dependency even though not listed in README

### ISSUE THREAD

**Issue by rodneyrod** [EionRobb/pidgin-opensteamworks#116]
Gnome Keyring is a hard dependency to this project, not having it installed results in a build failure.
The README should be updated to reflect this, or the code should be modified to make it an optional dependency.

**Comment by EionRobb** [comment]
Thanks for pointing that out. Have updated the readme. 
Gnome-keyring is only required at build time but optional at runtime. Blame it on telepathy-haze :)

**Comment by rodneyrod** [comment]
All good.
Just out of curiosity is there some flag I could use to ignore this dependency?
I don't have Telepathy installed so that's not an issue.

**Comment by EionRobb** [comment]
Not exactly, but you could -D__APPLE__ and make the plugin think you're on OSX, maybe?

**Comment by rodneyrod** [comment]
Alright, I'll give that a go.
Where exactly would I put that though?

**Comment by 07151129** [comment]
Add to Makefile:
`CFLAGS += -D__APPLE__`

**Comment by rodneyrod** [comment]
Thanks :)
