### ISSUE TITLE
Old releases 1.4 and 1.5 are visible in the releases directory

### ISSUE THREAD

**Issue by BoffinbraiN** [EionRobb/pidgin-opensteamworks#119]
OK, this issue was originally about a bug I was encountering, and then I found that 1.6.1 was available under the Releases section of the Github page. I was previously looking in the code section, under the `steam-mobile/releases` directory. There, you can find older versions, but not the newer ones. Maybe these should be deleted to avoid confusion?

**Comment by EionRobb** [comment]
Just popped in to see give advice about upgrading and saw the changed bug report :) 

The releases folder was added to source control as a work around for Google Code not providing download space any more. It's definitely time to delete the files out of the releases folder now.

**Comment by BoffinbraiN** [comment]
Yes, I figured it was ported over directly from Google. I'll leave this open so you can close it when you delete the folder from master.

I've also send a suggestion to GitHub to make the Releases page more prominent on project pages, and they have taken the feedback onboard for their updated navigation project.

**Comment by EionRobb** [comment]
:)
