### ISSUE TITLE
Package pidgin-opensteamworks for Debian

### ISSUE THREAD

**Issue by nodiscc** [EionRobb/pidgin-opensteamworks#121]
A Request for Packaging has been filed at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690465.
Packaging for Debian also allows downstream distributions such as Ubunutu to inherit the package.

**Comment by doctorlard** [comment]
I've got a commit that mostly works at doctorlard/pidgin-opensteamworks@9e5e4f5 but it needs a maintainer (not me!) and copyright notice, which is why it doesn't have a pull request yet. Feedback welcome, it would be nice to have this in upstream Debian and Ubuntu.

**Comment by doctorlard** [comment]
@EionRobb - thoughts on this - feel free to suggest or go ahead and make changes, re copyright and maintainer. Maybe we should get in contact with whoever is maintaining other similar packages in Debian/Ubuntu land.

**Comment by EionRobb** [comment]
@doctorlard GPLv3+ license.  Is it possible to leave the maintainer blank?  If not you can put in my details.  Send through a PR! :)

**Comment by nodiscc** [comment]
Is anyone working on this anymore?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690465 was inactive so it got closed

I still use pidgin-opensteamworks daily and would like to get it packaged.
https://github.com/doctorlard/pidgin-opensteamworks/commit/9e5e4f5 is still available so I will have a look and try to resume work from there, any help is welcome.

**Comment by nodiscc** [comment]
I'm no longer working on this since this plugin is no longer maintained (https://github.com/EionRobb/pidgin-opensteamworks/issues/206).
