### ISSUE TITLE
friend and group invites are indistinguishable

### ISSUE THREAD

**Issue by CapsAdmin** [EionRobb/pidgin-opensteamworks#123]
i always have to go to steamcommunity.com to make sure i'm not accepting any group invites

**Comment by EionRobb** [comment]
Ah yeah that's a pain.  Should be able to stop that coming through

**Comment by EionRobb** [comment]
https://github.com/EionRobb/pidgin-opensteamworks/commit/eb9016b7e7ca0c644a39f592660f7d4f6a99b819 should help
