### ISSUE TITLE
friend invite notficiation should show nickname and not the steamid

### ISSUE THREAD

**Issue by CapsAdmin** [EionRobb/pidgin-opensteamworks#124]
to figure out the steam id you should view profile info instead

**Comment by EionRobb** [comment]
Ah, this info isn't given to us when we get informed about the user being added, just the ID

I guess we could look it up in a separate request...

**Comment by Xylemon** [comment]
It would be great if this could be added, I hate having to log onto the Steam via the site or search the id to find out who added me.

**Comment by EionRobb** [comment]
Just added this now https://github.com/EionRobb/pidgin-opensteamworks/commit/184e83ecbb921c96472f8fa1bbaa61f8e6411453 :)

**Comment by Xylemon** [comment]
I can confirm this works! Along with removing people from pidgin, accepting, and deny friend requests. All seem to function now, great work!

**Comment by EionRobb** [comment]
Awesome, thanks for testing :)

I'll package up a new version so everyone else can enjoy it too

**Comment by CapsAdmin** [comment]
I also confirm that this is working. Thanks!
