### ISSUE TITLE
base64.h is not found when following build instructions on fedora 23

### ISSUE THREAD

**Issue by CapsAdmin** [EionRobb/pidgin-opensteamworks#129]
the solution on fedora 23 is to install nss-devel

**Comment by EionRobb** [comment]
The annoying bit is that the base64 header isn't even needed

**Comment by EionRobb** [comment]
Was it just that one header that was a problem, or were the others also a problem?

**Comment by CapsAdmin** [comment]
The three other headers exist in nss too. Where do you get these headers from?

**Comment by EionRobb** [comment]
Ok yeah, that was dumb of me to just remove the base64 header.  It should definitely need devel headers for NSS.

**Comment by EionRobb** [comment]
There ya go.  Thanks for reporting this :)

**Comment by xvitaly** [comment]
@CapsAdmin Just use `dnf builddep purple-libsteam.spec` and it will download and install all required dependencies. :-)
