### ISSUE TITLE
Looping captcha despite correct password, username, steam guard code - have steam mobile authenticator enabled

### ISSUE THREAD

**Issue by roblovelett** [EionRobb/pidgin-opensteamworks#131]
Tried logging in with both my verbal and steam id number for username. Correct password. Tried using my current steam guard code and generated 1-time use codes in advanced settings. When it tries to log in, I enter the correct CAPTCHA but it just loops to another one.

**Comment by EionRobb** [comment]
Unfortunately the steam servers don't tell us the difference between a bad password and a bad captcha.

Are you able to attach a debug log (Help->Debug Window) as you connect, as it might provide more info.

**Comment by roblovelett** [comment]
turns out I was using the wrong username. sorry for the confusion.
