### ISSUE TITLE
Linux makefile install target seemingly missing

### ISSUE THREAD

**Issue by stan423321** [EionRobb/pidgin-opensteamworks#137]
Tarball v. 1.6.1.

`sudo make install`
`make: Nothing to be done for 'install'.`

Manual look at Makefile showcases no rule for `install`, at least no straightforward one.

**Comment by xvitaly** [comment]
> Tarball v. 1.6.1.

Too outdated. Use latest from Git.

**Comment by hasufell** [comment]
> Don't use make install. Build and install package.

Nah, that's a bug
