### ISSUE TITLE
Cannot change status

### ISSUE THREAD

**Issue by Crypt-ix** [EionRobb/pidgin-opensteamworks#144]
Using Windows, doesn't let me change any of the status.

**Comment by EionRobb** [comment]
How do you mean?

The plugin lets you change your status, but it will only change your web/mobile status, not your Steam client status which gets priority over the web/mobile status.

**Comment by Xylemon** [comment]
Interestingly enough, I use the Web protocol and normally I can't set my status (this is with Steam closed), however if I leave my PC idle, the Steam status will be set "Away" via the Pidgin plugin. It's weird it can work that way but I can't manually set it "Away".

**Comment by Crypt-ix** [comment]
Yeah sorry for the  delayed reply, but I was talking about the client. My friends state that I'm always "Away" no matter what status I change it to. Was wondering if there could be a fix for this.

I was told there's another tool https://github.com/scholtzm/punk that actually allows you to select your status for steam client.

**Comment by Xylemon** [comment]
@Crypt-ix Wow does that client actually function fully without Steam? If so perhaps @EionRobb could study it to fix a few problems in the plugin.

**Comment by Crypt-ix** [comment]
@Xylemon I'll give it a go now and let you know. 

* Yep can confirm that it works brilliant, requires no installation it's fine right off the bat. Yes, it functions perfectly fine without steam installation (confirmed as it runs on my VPS).

It's pretty awesome you got your store page, notifications, pending trade offers and add friend

**Comment by Xylemon** [comment]
@Crypt-ix Thanks for sharing and testing it out, certainly looks like an interesting project to track. I hope it can be useful for other Steam related projects.

**Comment by Crypt-ix** [comment]
@EionRobb 
https://github.com/scholtzm/punk/blob/master/src/plugins/personastate/index.js#L186-L189
https://github.com/scholtzm/punk/blob/master/src/ui/menus/current-user-menu.js#L11-L13

Although this is for NodeJS I think.
I think you need to allow users to change persona states with "K_EPersonaChangeStatus"

**Comment by EionRobb** [comment]
That punk tool is using SteamKit, which is a replacement for the Steam client

The Steam Mobile api that this plugin uses has a different system entirely, hence the bit about only setting your web/mobile status and not the client status.

**Comment by EionRobb** [comment]
Sorry guys, going to have to close this issue because there's nothing more I can do in the mobile/web api for this
