### ISSUE TITLE
enabling steam account in pidgin causes steam app to lose connection

### ISSUE THREAD

**Issue by dpadgett** [EionRobb/pidgin-opensteamworks#147]
when i enable my steam account in pidgin, the steam app friends list goes empty and app says no connection.  this prevents playing of some games which require a steam connection.

**Comment by EionRobb** [comment]
Unfortunately I'm unable to replicate this, nor would there be anything I can do in the plugin to workaround this, as we're just making the same API calls that the mobile app does
