### ISSUE TITLE
Password in Plaintext

### ISSUE THREAD

**Issue by mrUlrik** [EionRobb/pidgin-opensteamworks#156]
I just complied using gcrypt and noticed my password was stored as plaintext in accounts.xml. Is this due to using gcrypt?

**Comment by xvitaly** [comment]
@mrUlrik Pidgin stores all passwords as plain text.

**Comment by 07151129** [comment]
Doesn't it use gnome keyring?

**Comment by EionRobb** [comment]
https://developer.pidgin.im/wiki/PlainTextPasswords

There are plugins available that let you use Gnome/KDE keyring or the Windows credential manager instead.
