### ISSUE TITLE
No incoming messages

### ISSUE THREAD

**Issue by sdfg2** [EionRobb/pidgin-opensteamworks#160]
Well I managed to get it installed after compiling with polarssl.

Everything works with the initial connection, and outgoing messages get sent.  I'll get a status update saying that the other person is composing a message, but after that, nothing.  No incoming messages, no status changes to users on my roster, my status doesn't get updated (if I set myself away), even though all my outgoing messages continue to get through.  Checking the logs, I do get the following

`13,311: 2017-04-22 19:16:18,779 INFO  libpurple: steam:getting url /ISteamWebUserPresenceOAuth/PollStatus/v0001
13,311: 2017-04-22 19:16:18,779 INFO  libpurple: steam:sending request data:
steamid=***********&umqid=**********&message=371&secidletime=0
13,311: 2017-04-22 19:16:18,779 INFO  libpurple: dnsquery:Performing DNS lookup for 23.195.77.152
13,311: 2017-04-22 19:16:18,779 INFO  libpurple: dnsquery:IP resolved for 23.195.77.152
13,311: 2017-04-22 19:16:18,779 INFO  libpurple: proxy:Attempting connection to 23.195.77.152
13,311: 2017-04-22 19:16:18,779 INFO  libpurple: proxy:Connecting to 23.195.77.152:80 with no proxy
13,311: 2017-04-22 19:16:18,779 INFO  libpurple: proxy:Connection in progress
13,311: 2017-04-22 19:16:18,800 INFO  libpurple: proxy:Connecting to 23.195.77.152:80.
13,311: 2017-04-22 19:16:18,800 INFO  libpurple: proxy:Connected to 23.195.77.152:80.
13,311: 2017-04-22 19:16:19,073 INFO  libpurple: steam:executing callback for /ISteamWebUserPresenceOAuth/PollStatus/v0001`

And that just repeats, every second.

**Comment by EionRobb** [comment]
Can you double-check the "Always use HTTPS" setting is enabled?

**Comment by sdfg2** [comment]
Sorry, missed this message.

I just tried registering the transport again (I'm using it with spectrum), and it worked.  I can't see how to set that setting though, where would I find it?  Just in case it's a transient bug.

**Comment by EionRobb** [comment]
Sorry, not sure how to set that setting through spectrum2

Glad it's working for you all right though :)
