### ISSUE TITLE
Feature-request: Sending message to multiple users at once

### ISSUE THREAD

**Issue by hjixl** [EionRobb/pidgin-opensteamworks#162]
There seems to be some sort script available for browsers to send message to multiple users at once, could this be dublicated for pidgin-opensteamworks as well? Maybe even turn it into chat-like?

https://steamcommunity.com/sharedfiles/filedetails/?id=840137082

**Comment by EionRobb** [comment]
I believe there's a plugin in the purple-plugin-pack for doing something like this, but it's a bit outside the scope of this plugin
