### ISSUE TITLE
libjson-glib-1.0.dll missing source

### ISSUE THREAD

**Issue by Kasijjuf** [EionRobb/pidgin-opensteamworks#167]
No source code is provided for [libjson-glib-1.0.dll](https://github.com/EionRobb/pidgin-opensteamworks/blob/master/steam-mobile/libjson-glib-1.0.dll). Please provide the source code.

**Comment by EionRobb** [comment]
http://ftp.gnome.org/pub/gnome/sources/json-glib/0.14/

**Comment by Kasijjuf** [comment]
The folder you link to contains two different versions of the software. Which is the corresponding source for [libjson-glib-1.0.dll](https://github.com/EionRobb/pidgin-opensteamworks/blob/master/steam-mobile/libjson-glib-1.0.dll)?

**Comment by EionRobb** [comment]
Oh, good point!

0.14.2 is what we have been using in the Facebook, Hangouts, Skype, etc plugins.  Looking at whats in the steam-mobile folder though, it might be 0.8.0 from http://ftp.gnome.org/pub/gnome/sources/json-glib/0.8/ in which case I need to do a version bump to the same libjson-glib as everything else uses.
