### ISSUE TITLE
Pidgin crashes when steam client is started

### ISSUE THREAD

**Issue by psukys** [EionRobb/pidgin-opensteamworks#169]
Steps to reproduce:

1. Run pidgin
2. Run steam
3. Verify pidgin crashes

- Pidgin 2.12.0-3.fc27 (libpurple 2.12.0)
- Plugins:
```
Plugin Information
...
Steam
	Author: Eion Robb <eionrobb@gmail.com>
	Version: 1.6.1
	Website: http://pidgin-opensteamworks.googlecode.com/
	ID String: prpl-steam-mobile
	Loadable: Yes
	Loaded: Yes
...
```

**Comment by EionRobb** [comment]
https://developer.pidgin.im/wiki/GetABacktrace

**Comment by psukys** [comment]
With debuginfo packages installed:
[pidgin-backtrace.log](https://github.com/EionRobb/pidgin-opensteamworks/files/1919806/pidgin-backtrace.log)

**Comment by EionRobb** [comment]
That's really weird.  The messaging stream is trying to process the steam id 103582791456010664, which isn't a valid id.

Are you also able to get a debug log by running pidgin with  --debug  just before the crash?

I'll add in some checks to make sure the steam id is valid before trying to process it, to help avoid this crash.

**Comment by EionRobb** [comment]
Ah ok, that id is for a clan, http://steamcommunity.com/gid/103582791456010664/ - but it shouldn't be triggering online/offline status updates.  Hopefully the debug log will reveal more about what steam is sending us.

**Comment by EionRobb** [comment]
Can you try compiling with the fix in https://github.com/EionRobb/pidgin-opensteamworks/commit/a97ca27a224a3b619a47f18ba23dcf12bbf0a459 to see if it stops crashing?

**Comment by psukys** [comment]
@EionRobb I tried it out, seems that pidgin does not crash with a compiled a97ca27

**Comment by EionRobb** [comment]
That's good news 👍 

Thanks for the update :)
