### ISSUE TITLE
Compiling fails on debian

### ISSUE THREAD

**Issue by truenicoco** [EionRobb/pidgin-opensteamworks#175]
Apparently the Makefile is not suited for compiling under a fairly regular debian stretch server install.

I could work my way out of this by adding `-I/usr/include/glib-2.0/glib/ -I/usr/include/gnome-keyring-1/ -I/usr/include/libpurple/ -I/usr/include/json-glib-1.0/ -I/usr/include/glib-2.0` to `gcc` parameters. I'm filing this bug in case someone else run into the same problem.

**Comment by EionRobb** [comment]
Good point @kgraefe

@truenicoco can you attach the output from when you run `make` without those modifications?

**Comment by truenicoco** [comment]
I'm sorry for the trouble, but apparently it is a `pkg-config` (or debian?) bug since it now compiles with the original `Makefile`. This is really surprising because I am 100% certain that I only had to install gnome-keyring and nss packages today. For instance, gllib-dev was already installed before today and couldn't be found by pkg-config:

```
$ zgrep libglib2.0-dev /var/log/dpkg.log.* 
[...]
/var/log/dpkg.log.8.gz:2017-11-07 20:07:21 status installed libglib2.0-dev:amd64 2.50.3-2
```

@kgraefe 

```
$ pkg-config --cflags glib-2.0
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
```

but I'm almost certain that it returned nothing earlier on this day. Anyway, this doesn't seem related to opensteamworks, please accept my apologies.
