### ISSUE TITLE
Compiling fails on Debian Buster (missing libgnome-keyring-dev)

### ISSUE THREAD

**Issue by TomTheDragon** [EionRobb/pidgin-opensteamworks#186]
Is there a way to compile the plugin, without installing deprecated packages?

**Comment by EionRobb** [comment]
ah, libgnome-keyring's been deprecated in favour of libsecret, right?  At the moment you'll need to use the deprecated package, but I'll look at getting rid of that \.

Just dropping this in as a note for migrating to the new API https://developer.gnome.org/libsecret/unstable/migrating.html

**Comment by EionRobb** [comment]
There we go, switched from gnome-keyring to libsecret.  It'll only be useful for people using telepathy-haze, if there are still any people using that

**Comment by TomTheDragon** [comment]
Thanks for the quick fix, it works now :)
