### ISSUE TITLE
Connection not fully over SSL/TLS even when "Always use HTTPS" is checked

### ISSUE THREAD

**Issue by nodiscc** [EionRobb/pidgin-opensteamworks#195]
I have a firewall blocking outbound port 80 and noticed the plugin was not fully working. I could send messages, but not receive. After some time the account would disconnect and the debug console shows  this message:

```
(20:00:59) proxy: Connecting to api.steampowered.com:80.
(20:00:59) proxy: Error connecting to api.steampowered.com:80 (Timeout).
(20:00:59) proxy: Connection attempt failed: Timeout
(20:00:59) steam: post_or_get_connect failure to /ISteamWebUserPresenceOAuth/PollStatus/v0001
(20:00:59) steam: post_or_get_connect_cb Timeout
(20:00:59) steam: fatal connection error
(20:00:59) connection: Connection error on 0xxxxxxxxxxxxxx (reason: 0 description: Server closed the connection.)
(20:00:59) account: Disconnecting account zzzzzz (0xxxxxxxxxxxxxx)
(20:00:59) connection: Disconnecting connection 0xxxxxxxxxxxxxx
```

After allowing outbound HTTP to `api.steampowered.com` communication works again both ways, and I no longer get disconnects.

I see there are a few references to port 80 hardcoded in https://github.com/EionRobb/pidgin-opensteamworks/blob/master/steam-mobile/steam_connection.c, but it's probably not as simple as replacing them with 443, is it?

**Comment by EionRobb** [comment]
I was going to say "no" but things might have changed since I implemented this protocol. It used to be that it would only do long-polling on 80 and short polling for content on 443, but that could be different now.

**Comment by nodiscc** [comment]
@EionRobb I take it you don't use this plugin anymore? I'd like to look again at this issue but it might take a while until I get some time to patch/rebuild/test everything.

**Comment by EionRobb** [comment]
I still use this plugin on a daily basis, yeah, but since I don't have a firewall blocking port 80 I haven't looked into it. 

Did you have a go at replacing all mentions of port 80 with 443?

**Comment by nodiscc** [comment]
I'm no longer working on this since this plugin is no longer maintained (https://github.com/EionRobb/pidgin-opensteamworks/issues/206).
