### ISSUE TITLE
SSL Connection Failed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EionRobb/pidgin-opensteamworks#28]
```
Attempting to log on and I get an error saying: "[Username] disconnected SSL 
Connection Failed"

Using Pidgin 2.10.3 w/ libsteam-debug 1.0 on Windows 7 Ultimate x64

```

Original issue reported on code.google.com by `73706...@gmail.com` on 26 Apr 2012 at 11:47

**Comment by RoseTheFlower** [comment]
It's happening again.

**Comment by Xylemon** [comment]
The Steam servers seem to be taking a dump today, which isn't too atypical. Just wait, and restart Pidgin when they seem to be more functional.
