### ISSUE TITLE
Status not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EionRobb/pidgin-opensteamworks#68]
```
What steps will reproduce the problem?
1. Connect to Steam account
2. Attempt to change status to anything besides "Online" or "Offline"

What is the expected output? What do you see instead?
The new status appears to take effect in pidgin, however, friends still just 
see me as "Online"

What version of the product are you using? On what operating system?
v1.3 with Pidgin 2.10.7-3.fc19
on Fedora 19 x86_64

Please provide any additional information below.
I can still manually set my status in the full Steam client, however, it would 
be nice not to have to open that, and to have my status switch to "Away" 
automatically when I'm idle.
```

Original issue reported on code.google.com by `Barthis...@gmail.com` on 6 Nov 2013 at 7:21

**Comment by Xylemon** [comment]
Is this still unfixable? I would really like the ability to set my status as "away" or something on Steam. Far too many people try contacting me thinking I'm actually there

**Comment by EionRobb** [comment]
@Xylemon  Unfortunately nothing more can be done; the desktop client status overrides the web client status overrides the mobile client status.

You could try setting your status to Offline in the desktop client and choosing "Web" from the "Identify as" setting in the Advanced tab of the account settings.

**Comment by Xylemon** [comment]
@EionRobb Well I'd just like to have the ability to set my status for the Steam protocol with Pidgin when the Steam client isn't open (as I don't leave it open most of the time). But sadly, even identifying as "Web" in the advanced settings seems to have changed nothing. In fact I still am seen as a mobile user to my friends.

**Comment by EionRobb** [comment]
@Xylemon you'll need to reconnect after changing the "Identify as" setting for it to apply, sorry.  I should probably add a notice for that in the plugin.

You can still set your status using the status dropdown at the bottom of the buddy list, eg by setting New Status and customising it for Steam to be 'Snooze' or whatever

**Comment by Xylemon** [comment]
@EionRobb I have gone offline then back online, disabled and re-enabled, and even restarted Pidgin itself, still seen as a mobile user and no change in status.

**Comment by Xylemon** [comment]
@EionRobb Update, it seems the "Web" protocol switching worked. However, I am still sadly unable to set "Away" or "Busy" under Pidgin without the Steam client open.
